# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Configuration cache disabled for Loom compatibility
org.gradle.configuration-cache=false

# Global Mod Properties
mod_version=1.2.1
maven_group=com.easywp

# Shared Tooling Versions
loom_version=1.17-SNAPSHOT
loader_version=0.19.3
loom.ignoreDependencyLoomVersionValidation=true
