plugins {
	id 'net.fabricmc.fabric-loom'
}

version = "${project.mod_version}+${project.minecraft_version_suffix}"
group = project.maven_group
base.archivesName = "easywp"

loom {
	splitEnvironmentSourceSets()

	mods {
		"easywp" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets {
	main {
		java.srcDirs += project(":common").file("src/main/java")
		resources.srcDirs += project(":common").file("src/main/resources")
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation project(":common")
}

processResources {
	def version = project.mod_version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
